apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: LoadBalancer  
  selector:
    app: active  
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 3000 
    - protocol: TCP
      port: 8001       
      targetPort: 8001 
